stoic-front/brokers/urls.py
from django.urls import path
from . import views

app_name = 'brokers'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('schema/<broker_type>', views.schema, name='schema')
]

stoic-front/myfront/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Stoic Front API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="Unlicensed"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('brokers/', include('brokers.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

stoic-front/brokers/models.py
from django.db import models

# Create your models here.

stoic-front/brokers/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, Form
from django_jsonforms.forms import JSONSchemaField

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class SingUpForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class BrokerForm(forms.Form):
    _type = forms.ChoiceField(label='Broker Type', widget= forms.Select(attrs={'id':'broker_type'}))
    _id = forms.CharField(label='Broker id', max_length=30, widget=forms.TextInput(attrs={'id':'broker_id'}))
    #text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':25}))

class BrokerEditForm(forms.Form):
    _type = forms.ChoiceField(label='Broker Type', widget=forms.Select(attrs={'id':'edit_broker_type'}))
    _id = forms.CharField(label='Broker Id', widget=forms.TextInput(attrs={'id':'edit_broker_id'}))
    #_type = forms.CharField(widget=forms.HiddenInput())
    #text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':25}))

stoic-front/projects/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class SingUpForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class ProjectForm(forms.Form):
    name = forms.CharField(label='Project name', max_length=30)
    file = forms.FileField(label='Project file')


class ProjectEditForm(forms.Form):
    name = forms.CharField(widget=forms.HiddenInput())
    text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':25}))

stoic-front/brokers/views.py
from django.shortcuts import render
import os
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from .forms import BrokerForm, BrokerEditForm
from django.http import *
import uuid
import shutil
import json
from .middlewares import *
import requests
from django_jsonforms.forms import JSONSchemaForm

@login_required
def index(request):
    brokers = []
    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()
    print(brokers)
    
    if request.headers.get('Accept') != 'application/json':
        #form = JSONSchemaForm(schema=schema, options={"theme": "bootstrap4"}, ajax=True)
        new_form = BrokerForm()
        edit_form = BrokerEditForm()
        new_form.fields['_type'].choices = (('watson', 'Watson'), ('fiware', 'Fiware'))
        edit_form.fields['_type'].choices = (('watson', 'Watson'), ('fiware', 'Fiware'))
        return render(request, 'brokers/index.html', { 'brokers': brokers, 'new_form': new_form, 'edit_form': edit_form })
    else:
        return JsonResponse(data=brokers,safe=False)

@login_required
@csrf_exempt
def new(request):
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        try:
            broker = json.loads(data)
        except:
            pass
        else:
            r = requests.post("http://localhost:8080/broker", data=json.dumps(broker), headers={'content-type':'application/json'})
        print(r.json())
        return HttpResponseRedirect('/brokers')

@login_required
@csrf_exempt
def edit(request):
    if request.method == 'GET':
        data = {}
        data['id'] = request.GET["id"]
        data['type'] = request.GET['type']
        r = requests.get("http://localhost:8080/broker/" + data['id'])
        attrs = r.json()
        attrs.pop('_id')
        attrs.pop('type')
        data['text'] = json.dumps(attrs)
        form = BrokerEditForm(initial = data)
        print(form)
        return render(request, 'brokers/edit.html', { 'data': data, 'form': form })
    elif request.method == 'POST':
        broker = json.loads(request.body.decode('utf-8'))
        r = requests.put("http://localhost:8080/broker", json.dumps(broker), headers={'content-type':'application/json'})
        return HttpResponseRedirect('/brokers')

@login_required
def delete(request):
    if request.method == 'GET':
        _id = request.GET['id']
        r = requests.delete('http://localhost:8080/broker/' + _id)
        r.json()
        return HttpResponseRedirect('/brokers')

@login_required
def schema(request, broker_type):
    if request.method == 'GET':
        r = requests.get('http://localhost:8080/broker/schema/' + broker_type)
        return JsonResponse(r.json(), safe=False)

stoic-front/brokers/templates/brokers/edit.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Broker {{ data.id }}</h1>
<script>
function prettify(sel) {
    text = JSON.parse(document.querySelector(sel).innerHTML.replace(/'/g, '"'))
    document.querySelector(sel).innerHTML = JSON.stringify(text, null, 4)
}


function minify(sel) {
    text = JSON.parse(document.querySelector(sel).innerHTML.replace(/'/g, '"'))
    document.querySelector(sel).innerHTML = JSON.stringify(text, null, 0)
}
</script>
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>Save</button>
        <button onclick="prettify('#id_text')" type="button" class="btn btn-warning">Prettify</button>
        <button onclick="minify('#id_text')" type="button" class="btn btn-warning">Minify</button>
    </div>
</form>
{% endblock %}

stoic-front/brokers/templates/brokers/index.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h2 class="mb-4">Platforms</h2>
<input class="form-control" id="brokers-filter" type="text" placeholder="Search..">
<br>
<div class="table-responsive">
<table class="table table-bordered table-striped">
  <thead class="bg-primary stoic-color">
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Type</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody id="brokers-table">
    {% for broker in brokers %}
    <tr>
      <th scope="row">{{ forloop.counter0 }}</th>
      <td class="align-middle">{{ broker.id }}</td>
      <td class="align-middle">{{ broker.type }}</td>
      <td class="align-middle">
            <button data-broker="{{ broker.id }}" type="button" class="btn btn-primary btn-sm" data-toggle="modal"
              data-target="#new_broker"><i class="fa fa-edit" aria-hidden="true"></i></button>
            <button onclick="location.href='{% url 'brokers:delete' %}?id={{ broker.id }}';" type="button"
              class="btn btn-danger btn-sm"><i class="fas fa-trash" aria-hidden="true"></i></button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot class="bg-primary stoic-color">
  <tr>
    <td scope="col">#</td>
    <td scope="col">ID</td>
    <td scope="col">Type</td>
    <td scope="col">Action</td>
  </tr>
</tfoot>
</table>
</div>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_broker">New broker</button>
<div class="modal fade" id="new_broker" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">New broker</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="new_broker_form" method="post" enctype="multipart/form-data" action="{% url 'brokers:new' %}">
          {% csrf_token %}
          {{ new_form.errors }}
          {{ new_form.media }}
          {{ new_form|bootstrap }}
          <div id="credentials"></div>
        </form>
      </div>
      <div class="modal-footer">
        <button id="new_broker_submit" type="button" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

<!-- Handlebars -->
<script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.js"></script>

<!-- Flatpickr -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.3/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.3/dist/flatpickr.min.js"
  integrity="sha256-/irFIZmSo2CKXJ4rxHWfrI+yGJuI16Z005X/bENdpTY=" crossorigin="anonymous"></script>

<!-- JSON-Editor -->
<script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js"></script>
<script>
  function load_modal(modal, title, form_action, submit_text, submit_event) {
    modal.find('.modal-title').text(title)
    //modal.find('.modal-body input').val(brokerId)
    modal.find('.modal-body form').attr('action', form_action)
    let submit = modal.find('#new_broker_submit')
    submit.text(submit_text)
    submit.click(submit_event)
  }

  $(() => {
    jsoneditor = null
    edit_jsoneditor = null

    $("#brokers-filter").on("keyup", function () {
      var value = $(this).val().toLowerCase();
      $("#brokers-table tr").filter(function () {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });

    $('#new_broker').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var brokerId = button.data('broker') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
          let submit_event = () => {
              console.log("OOIIIIII")
              var broker_form = modal.find("#new_broker_form")
              if (!broker_form[0].reportValidity())
                return;
              let broker = jsoneditor.getValue()
              let body = {
                id: $('#broker_id').val(),
                type: $('#broker_type').val()
              }
              body = Object.assign(body, broker)

              $.ajax({
                method: "POST",
                url: (brokerId == undefined)?"{% url 'brokers:new' %}":"{% url 'brokers:edit' %}",
                headers: {
                  'content-type': 'application/json'
                },
                data: JSON.stringify(body)
              }).done(resp => {
                location.href = "{% url 'brokers:index' %}"
              });
          }
        if (brokerId == undefined) {
          $('#broker_type').prop( "disabled", false );
          $('#broker_id').prop( "disabled", false );
          $("#broker_type").trigger('change')
          load_modal(
            modal,
            'New broker',
            '{% url 'brokers:new' %}',
            'New broker',
            submit_event
          )
          modal.find('.modal-body input').val(brokerId)
        } else {
          load_modal(
            modal,
            'Edit ' + brokerId,
            '{% url 'brokers:edit' %}',
            'Save',
            submit_event
          )

            $.ajax({
              method: "GET",
              url: "{% url 'brokers:index' %}",
              headers: {
                'Accept': 'application/json'
              }
            }).done(brokers => {
              console.log(brokers)
              var broker = {}
              brokers.forEach(b => {
                if (b.id == brokerId) {
                  broker = b
                  return
                }
              });

            $('#broker_type').val(broker.type)
            $('#broker_id').val(broker.id)
            $('#broker_type').triggerHandler('change');
            delete broker.id
            delete broker.type
            jsoneditor.setValue(broker)
            $('#broker_type').prop( "disabled", true );
            $('#broker_id').prop( "disabled", true );
          })
        }
    })

    $("#broker_type").change((event) => {
      let brokerType = $(event.target).find(":selected").val()
      console.log("Valor Escolhido foi: " + brokerType);
      $.ajax({
        method: "GET",
        url: "http://"+ location.host +"/brokers/schema/" + brokerType,
        async: false
      }).done((data) => {
        console.log(data)
        let element = document.getElementById('credentials');
        let options = {
          "theme": "bootstrap4",
          "template": "handlebars",
          "iconlib": "fontawesome4",
          "form_name_root": "broker",
          "schema": data
        }
        if (jsoneditor) {
          jsoneditor.destroy()
        }
        jsoneditor = new JSONEditor(element, options);
      });
    })

  });
</script>
{% endblock %}

stoic-front/brokers/templates/brokers/new.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Devices</h1>
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    {% if action == 'new' %}
        <input type="submit" role="button" class="btn btn-primary" value="Create">
    {% else %}
        <input type="submit" role="button" class="btn btn-primary" value="Update">
    {% endif %}
</form>
{% endblock %}