stoic-front/brokers/urls.py
from django.urls import path
from . import views

app_name = 'brokers'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('schema/<broker_type>', views.schema, name='schema')
]

stoic-front/myfront/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Stoic Front API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="Unlicensed"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('brokers/', include('brokers.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

stoic-front/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('activate', views.activate, name='activate')
]

stoic-front/projects/models.py
from django.db import models

# Create your models here.

stoic-front/projects/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class SingUpForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=30, widget=forms.PasswordInput)

class ProjectForm(forms.Form):
    name = forms.CharField(label='Project name', max_length=30)
    file = forms.FileField(label='Project file')


class ProjectEditForm(forms.Form):
    name = forms.CharField(widget=forms.HiddenInput())
    text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':25}))

stoic-front/projects/views.py
from django.shortcuts import render
import os
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .forms import ProjectForm, ProjectEditForm
from django.http import *
import uuid
import shutil
import json
from .middlewares import *

@login_required
def index(request):
    workspace = './workspace/%s' % request.user.id
    files = []
    if not os.path.exists(workspace):
        os.makedirs(workspace)
        os.mknod(workspace + '/.config')
        with open(workspace + '/.config', 'wb') as config:
            config.write("{}".encode())
    active = get_active(request)
    # r=root, d=directories, f = files
    for r, d, f in os.walk(workspace):
        for directory in d:
            ts = int(os.path.getmtime(workspace + '/' + directory))
            files.append({
                'name': directory,
                'last_modified': datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'),
                'active': True if active == directory else False
            })
    print(files)
    return render(request, 'projects/index.html', { 'files': files, 'form': ProjectForm(), 'active': active })

@login_required
def new(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        workspace = './workspace/%s' % request.user.id
        f = request.FILES['file']
        if form.is_valid():
            f = request.FILES['file']
            #with open(workspace + '/' + str(uuid.uuid1()) + '.json', 'wb+') as destination:
            if not os.path.exists(workspace + '/' + form.cleaned_data['name']):
                name = form.cleaned_data['name']
            else:
                i = 0
                while os.path.exists(workspace + '/' + form.cleaned_data['name'] + '(%s)' % i):
                    i += 1
                name = form.cleaned_data['name'] + "(%s)" % i
            os.makedirs(workspace + '/' + name)
            with open(workspace + '/' + name + '/project.json', 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            return HttpResponseRedirect('/projects')
        else:
            print("Not valid")

@login_required
def edit(request):
    workspace = './workspace/%s' % request.user.id
    if request.method == 'GET':
        data = {}
        data['name'] = request.GET["name"]
        with open(workspace + '/' + data['name'] + '/project.json', "rb") as file:
            data['text'] = file.read().decode()
        form = ProjectEditForm(initial = data)
        print(form)
        return render(request, 'projects/edit.html', { 'data': data, 'form': form, 'active': get_active(request) })
    elif request.method == 'POST':
        form = ProjectEditForm(request.POST)
        if form.is_valid():
            with open(workspace + '/' + form.cleaned_data['name'] + '/project.json', "wb") as file:
                file.write(form.cleaned_data.get('text').encode())
            return HttpResponseRedirect('/projects')
        else:
            print("Not valid")

@login_required
def delete(request):
    if request.method == 'GET':
        name = request.GET['name']
        workspace = './workspace/%s' % request.user.id
        config = workspace + '/.config'
        with open(config, 'r') as file:
            cfg = json.loads(file.read().strip())
            if "active" in cfg:
                active = cfg["active"]
            else:
                active = None
        if active == name:
            cfg.pop('active')
            with open(config, "w+") as file:
                file.truncate()
                json.dump(cfg, file)
        if os.path.exists(workspace + '/' + name):
            shutil.rmtree(workspace + '/' + name)
        else:
            print("The file does not exist")
        return HttpResponseRedirect('/projects')

@login_required
def activate(request):
    # global brokers
    workspace = './workspace/%s' % request.user.id
    if request.method == 'GET':
        proj = request.GET["name"]
        if os.path.exists(workspace + '/' + proj):
            workspace = './workspace/%s' % request.user.id
            config = workspace + '/.config'
            with open(config, "r") as file:
                cfg = json.load(file)
                cfg["active"] = proj
                '''
                try:
                    brokers
                except NameError:
                    pass
                else:
                    del brokers
                brokers = {}
                with open(workspace + '/%s/%s' % (proj, "project.json"), "r") as proj_file:
                    p = json.load(proj_file)
                    for broker, content in p['brokers'].items():
                        _type = content['type']
                        if _type == 'fiware':
                            mw = fiware_middleware
                        elif _type == 'watson':
                            mw = watson_middleware
                        brokers[broker] = mw(content, None)
                '''
            with open(config, "w+") as file:
                file.truncate()
                json.dump(cfg, file)
        return HttpResponseRedirect('/projects')

def get_active(request):
    workspace = './workspace/%s' % request.user.id
    with open(workspace + '/.config', 'r') as config:
        cfg = json.loads(config.read().strip())
        if "active" in cfg:
            active = cfg["active"]
        else:
            active = None
    return active

stoic-front/projects/templates/projects/edit.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Project {{ data.name }}</h1>
<script>
function prettify(sel) {
    text = JSON.parse(document.querySelector(sel).innerHTML.replace(/'/g, '"'))
    document.querySelector(sel).innerHTML = JSON.stringify(text, null, 4)
}


function minify(sel) {
    text = JSON.parse(document.querySelector(sel).innerHTML.replace(/'/g, '"'))
    document.querySelector(sel).innerHTML = JSON.stringify(text, null, 0)
}
</script>
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>Save</button>
        <button onclick="prettify('#id_text')" type="button" class="btn btn-warning">Prettify</button>
        <button onclick="minify('#id_text')" type="button" class="btn btn-warning">Minify</button>
    </div>
</form>
{% endblock %}

stoic-front/projects/templates/projects/index.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Projects</h1>
<input class="form-control" id="devices-filter" type="text" placeholder="Search..">
<br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">File</th>
      <th scope="col">Last Modified</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody id="devices-table">
    {% for file in files %}
    <tr>
      <th scope="row">{{ forloop.counter0 }}</th>
      <td class="align-middle"><a href="{% url 'projects:edit' %}?name={{ file.name }}">{{ file.name }}</a></td>
      <td class="align-middle">{{ file.last_modified }}</td>
      <td class="align-middle">
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group mr-2" role="group" aria-label="First group">
            {% if not file.active %}
            <button onclick="location.href='{% url 'projects:activate' %}?name={{ file.name }}';" type="button" class="btn btn-success btn-sm"><i class="fa fa-play" aria-hidden="true"></i></button>
            {% endif %}
            <button onclick="location.href='{% url 'projects:delete' %}?name={{ file.name }}';" type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
          </div>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_project">New project</button>
<div class="modal fade" id="new_project" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">New project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="new_project_form" method="post" enctype="multipart/form-data" action="{% url 'projects:new' %}">
          {% csrf_token %}
          {{ form.errors }}
          {{ form|bootstrap }}
        </form>
      </div>
      <div class="modal-footer">
        <button id="new_project_submit" type="button" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function(){
      $("#devices-filter").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#devices-table tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });

      $('#new_project').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) // Button that triggered the modal
          var recipient = button.data('project') // Extract info from data-* attributes
          // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
          // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
          var modal = $(this)
          if (recipient != undefined) {
            modal.find('.modal-title').text('New message to ' + recipient)
            modal.find('.modal-body input').val(recipient)
          }
          modal.find('#new_project_submit').click(function() {
            if (modal.find("#new_project_form")[0].reportValidity())
              modal.find("#new_project_form").trigger('submit')
          })
          console.log(modal.find('#new_project_submit'))
        })
      });
</script>
{% endblock %}

stoic-front/projects/templates/projects/new.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Devices</h1>
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    {% if action == 'new' %}
        <input type="submit" role="button" class="btn btn-primary" value="Create">
    {% else %}
        <input type="submit" role="button" class="btn btn-primary" value="Update">
    {% endif %}
</form>
{% endblock %}