stoic-front/brokers/urls.py
from django.urls import path
from . import views

app_name = 'brokers'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('schema/<broker_type>', views.schema, name='schema')
]

stoic-front/manager/urls.py
from django.urls import path, re_path
from . import views

app_name = 'manager'

urlpatterns = [
    # -- BROKERS --
    #path('brokers', views.brokers_index, name='brokers_index'),
    #path('brokers/new', views.brokers_new, name='brokers_new'),
    #path('brokers/delete', views.brokers_delete, name='brokers_delete'),
    # -- DEVICES --
    path('devices', views.devices_index, name='devices_index'),
    path('devices/new', views.devices_new, name='devices_new'),
    path('devices/delete', views.devices_delete, name='devices_delete'),
    # -- ENTIDADES --
    path('entities', views.entities_index, name='entities_index'),
    path('entities/new', views.entities_new, name='entities_new'),
    path('entities/edit', views.entities_edit, name='entities_edit'),
    path('entities/delete', views.entities_delete, name='entities_delete'),
    # -- ASSOCIATIONS --
    path('associations', views.associations_index, name='associations_index'),
    path('associations/new', views.associations_new, name='associations_new'),
    path('associations/delete', views.associations_delete, name='associations_delete'),
    # -- TASKS --
    path('tasks', views.tasks_index, name='tasks_index'),
    path('tasks/new', views.tasks_new, name='tasks_new'),
    path('tasks/edit', views.tasks_edit, name='tasks_edit'),
    path('tasks/delete', views.tasks_delete, name='tasks_delete'),
    # -- DASHBOARD --
    path('dashboard', views.dashboard_index, name='dashboard_index'),
    path('dashboard/update', views.dashboard_update)
]
'''
Autorização para utilizar a reserva do auxilio a pesquisa
Encaminhar a solicitação pelo sistema Agilis fapesp.br/rt 21 de dezembro
'''

stoic-front/myfront/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Stoic Front API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="Unlicensed"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('brokers/', include('brokers.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

stoic-front/manager/models.py
from django.db import models

stoic-front/manager/forms.py
from django import forms

class DeviceForm (forms.Form):
    broker = forms.ChoiceField(label='Broker')
    _type = forms.CharField(label='Type', max_length=30)
    _id = forms.CharField(label='ID', max_length=30)
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'rows':5}), max_length=100)

class EntityForm (forms.Form):
    brokers = forms.MultipleChoiceField(label='Brokers', widget=forms.SelectMultiple(attrs = {'name':'brokers','class':'selectpicker'}))
    _type = forms.CharField(label='Type', max_length=30, widget=forms.TextInput(attrs={'id':'entity_type'}))
    _id = forms.CharField(label='ID', max_length=30, widget=forms.TextInput(attrs={'id':'entity_id'}))

class AttributeForm (forms.Form):
    _name = forms.CharField(label='Type', max_length=30)
    _value = forms.CharField(label='Type', max_length=30)
    _type = forms.CharField(label='Type', max_length=30)
    _metadata = forms.CharField(label='Type', max_length=30)

# class AssociationForm (forms.Form):
#     broker = forms.CharField(label='Broker', max_length=30)
#     device_type = forms.CharField(label='Device Type', max_length=30)
#     device_id = forms.CharField(label='Device ID', max_length=30)
#     entity_type = forms.CharField(label='Entity Type', max_length=30)
#     entity_id = forms.CharField(label='Entity ID', max_length=30)

class AssociationForm (forms.Form):
    broker = forms.ChoiceField(label='Broker ID', widget=forms.Select(attrs={'id':'broker_id'}))
    device_type = forms.ChoiceField(label='Device Type', widget=forms.Select(attrs={'id':'device_type'}))
    device_id = forms.ChoiceField(label='Device ID', widget=forms.Select(attrs={'id':'device_id'}))
    entity_type = forms.ChoiceField(label='Entity Type', widget=forms.Select(attrs={'id':'entity_type'}))
    entity_id = forms.ChoiceField(label='Entity ID', widget=forms.Select(attrs={'id':'entity_id'}))

class MappingForm (forms.Form):
    device_attr = forms.CharField(label='Type', max_length=30)
    entity_attr = forms.CharField(label='Type', max_length=30)
    entity_attr_type = forms.CharField(label='Type', max_length=30)

class TaskForm(forms.Form):
    broker = forms.ChoiceField(label='Broker ID', widget=forms.Select(attrs={'id':'broker_id'}))
    #text = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':25}))

class TaskEditForm(forms.Form):
    broker = forms.ChoiceField(label='Broker ID', widget=forms.Select(attrs={'id':'edit_broker_id'}))

stoic-front/manager/views.py
from django.shortcuts import render
from django.http import *

from .middlewares import *
from .elements import *
from .forms import DeviceForm, EntityForm, AssociationForm, TaskForm, TaskEditForm
import re

from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.decorators import login_required

from django.urls import reverse

from requests import request
'''
wiotp_broker = {
    "id": "broker1",
    "type": "watson",
    "url": "http://gvng6v....",
    "description": "desc",
    "auth": {
        "key": "a-gv6isn-xehobeg6qr",
        "token": "Lzn&I7Id6oqqKwjDkA"
    },
    "mqtt": {
        "port": 1883,
        "transport": "tcp|websockets",
        "cleanStart": True|False,
        "sessionExpiry": 3600,
        "keepAlive": 60
    },
    "watson": {
        "org": "gv6isn"
    },
    "cloudant": {
        'user': "6c505913-4696-4168-b63c-4354e4b13730-bluemix",
        'password': "ec07709b77140b43000189bf4c2ba78db446798860c55bfa80f19b7c2cc84aa3",
        'url': "https://6c505913-4696-4168-b63c-4354e4b13730-bluemix:ec07709b77140b43000189bf4c2ba78db446798860c55bfa80f19b7c2cc84aa3@6c505913-4696-4168-b63c-4354e4b13730-bluemix.cloudantnosqldb.appdomain.cloud",
        'db_entities': 'stoic_entities',
        'db_associations': 'stoic_associations',
        'db_actions': 'stoic_actions',
        'db_triggers': 'stoic_triggers',
        'db_tasks': 'stoic_tasks'
    }
}

f_broker = {
    "iota": {
        'url': 'http://localhost:4061/iot',
        'headers': {
            'fiware-service': 'stoic',
            'fiware-servicepath': '/',
            'cache-control': "no-cache"
        }
    },
    "orion": {
        "url": 'http://localhost:1026'
    },
    "cygnus": {
        "url": 'http://127.0.0.1:5050',
        'notify_root': '/notify'
    },
    "mongodb": {
        "url": "mongodb://localhost:27017/"
    },
    "historical": {
        "activate": True
    }
}

f_obj = fiware_middleware(f_broker, None)
'''
@login_required
def brokers_index(request):
    #broker_form = BrokerForm()
    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()

    broker_form = BrokerForm()
    broker_form.fields['_type'].choices = [(0, 'Watson'), (1, 'Fiware')]
    return render(request, 'brokers/index.html', { 'brokers': brokers, 'form': broker_form })
    

@login_required
def devices_index(request):
    #devices = f_obj.list_devices()
    form = DeviceForm()
    #print(update_brokers(request))
    # try:
    #     brokers
    # except NameError:
    #     update_brokers(request)
    # devices = []
    # for name, broker in brokers.items():
    #     d = broker.list_devices()
    #     for el in d:
    #         el['broker'] = name
    #     devices += d
    # if 'Content-Type' in request.headers:
    #     if request.headers['Content-Type'] == 'application/json':
    #         return devices
    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()
    choices = []
    for b in brokers:
        choices.append((b['id'], b['id'] + " [" + b['type'] + "]"))
    form.fields['broker'].choices = choices
    r = requests.get('http://localhost:8080/device')
    devices = r.json()
    new_devices = []
    for broker, devices_list in devices.items():
        for d in devices_list:
            d['broker'] = broker
            new_devices.append(d)
    if request.headers.get('Accept') == 'application/json':
        return JsonResponse(data = new_devices, safe = False)  
    return render(request, 'devices/index.html', { 'devices': new_devices, 'form': form })
    #return render(request, 'devices/index.html', { 'devices': new_devices, 'form': form })

@login_required
def devices_new(request):
    if request.method == 'GET':
        form = DeviceForm()
        return render(request, 'devices/new.html', { 'form': form, 'action': 'new' })
    elif request.method == 'POST':
        form = DeviceForm(request.POST)

        #if form.is_valid():
        _type = request.POST.get('_type')
        _id = request.POST.get('_id')
        description = request.POST.get('description')
        _broker = request.POST.get('broker')
        # try:
        #     brokers
        # except NameError:
        #     update_brokers(request)
        #brokers[_broker].create_device(Device(_type, _id))
        headers = {
            "broker": _broker,
            "content-type": "application/json"
        }
        r = requests.post("http://localhost:8080/device", data=json.dumps(Device(_type, _id, description).to_dict()), headers = headers)
        print(r.json())
        #f_obj.create_device(Device(_type,_id, description))
        return HttpResponseRedirect('/manager/devices')

@login_required
def devices_delete(request):
    if request.method == 'GET':
        _type = request.GET["type"]
        _id = request.GET["id"]
        _broker = request.GET['broker']
        # try:
        #     brokers
        # except NameError:
        #     update_brokers(request)
        r = requests.delete("http://localhost:8080/device/" + _type + "_" + _id, headers={'broker':_broker})
        if r.json():
            return HttpResponseRedirect('/manager/devices')
        else:
            return HttpResponseBadRequest(content='Error when trying to delete the device (%s:%s)' % (_type, _id))
    return HttpResponseBadRequest(content='Method %s not allowed. Use GET' % request.method)

@login_required
def entities_index(request):
    #devices = f_obj.list_devices()
    entity_form = EntityForm()

    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()
    choices = []
    for b in brokers:
        choices.append((b['id'], b['id'] + " [" + b['type'] + "]"))
    #entity_form.fields['broker'].choices = choices
    entity_form.fields['brokers'].choices = choices
    if request.headers.get('Accept') != 'application/json':
        r = requests.get("http://localhost:8080/entity", params=dict(clustered = True))
        entities = r.json()
    else:
        if request.GET.get('clustered') == 'true':
            r = requests.get("http://localhost:8080/entity", params=dict(clustered = True))
            entities = r.json()
        else:
            r = requests.get("http://localhost:8080/entity")
            old_entities = r.json()
            entities = []
            for broker, ents in old_entities.items():
                for entity in ents:
                    entity['broker'] = broker
                    entities.append(entity)
    if r.status_code >= 300:
        return JsonResponse(data = dict(status = "error", message = r.text))
    if request.headers.get('Accept') == 'application/json':
        return JsonResponse(data = entities, safe = False)
    return render(request, 'entities/index.html', { 'entities': entities, 'form': entity_form })

@csrf_exempt
@login_required
def entities_new(request):
    if request.method == 'GET':
        form = EntityForm()
        return render(request, 'entities/new.html', { 'form': form, 'action': 'new' })
    elif request.method == 'POST':
        entity = json.loads(request.body)
        attrs = entity.pop("attrs")
        brokers = entity.pop("brokers")
        for attr in attrs:
            if 'metadata' in attr:
                if not isinstance(attr['metadata'], dict):
                    attr['metadata'] = json.loads(attr['metadata'])
            entity[attr.pop("name")] = attr
        #for broker in brokers:
        headers = {
            'content-type': 'application/json',
            'brokers': ','.join(brokers)
        }
        r = requests.post("http://localhost:8080/entity",data=json.dumps(entity),headers=headers)
        print(r.json())
        return HttpResponseRedirect('/manager/entities')

@csrf_exempt
@login_required
def entities_edit(request):
    entity = json.loads(request.body)
    attrs = entity.pop("attrs")
    brokers = entity.pop("brokers")

    # attrs.append(dict(
    #     name="tangle",
    #     type="boolean",
    #     value=True
    # ))
    for attr in attrs:
        entity[attr.pop("name")] = attr
    for broker in brokers:
        headers = {
            'content-type': 'application/json',
            'broker': broker
        }
        r = requests.put("http://localhost:8080/entity",data=json.dumps(entity),headers=headers)
        print(r.text)
    return HttpResponseRedirect(reverse('manager:entities_index'))

@login_required
def entities_delete(request):
    if request.method == 'GET':
        _type = request.GET.get("type")
        _id = request.GET.get("id")
        _brokers = request.GET.get('brokers')
        # try:
        #     brokers
        # except NameError:
        #     update_brokers(request)

        r = requests.delete("http://localhost:8080/entity/" + _id, headers=dict(brokers = _brokers), params=dict(type = _type))
        if r.status_code >= 200 and r.status_code < 300:
            return HttpResponseRedirect('/manager/entities')

        # for broker in _brokers:
        #     headers = { 'broker': broker }
        #     r = requests.delete("http://localhost:8080/entity/" + _id, headers=headers, params=dict(type = _type))
        #     if not r.json():
        #         return HttpResponseBadRequest(content='Error when trying to delete the entity (%s:%s)' % (_type, _id))
        #return HttpResponseRedirect('/manager/entities')
    return HttpResponseBadRequest(content='Method %s not allowed. Use GET' % request.method)

@login_required
def associations_index(request):
    association_form = AssociationForm()
    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()
    choices = []
    for b in brokers:
        choices.append((b['id'], b['id'] + " [" + b['type'] + "]"))
    association_form.fields['broker'].choices = choices

    r = requests.get("http://localhost:8080/broker")
    brokers = r.json()
    associations = []
    for broker in brokers:
        headers = { 'broker':broker['id'] }
        r = requests.get("http://localhost:8080/association", headers=headers)

stoic-front/manager/templates/associations/index.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h2 class="mb-4">Links</h2>
<input class="form-control" id="devices-filter" type="text" placeholder="Search..">
<br>
<div class="alert alert-primary" role="alert">
  Fiware platform supports the association of a device to only one entity.
</div>
<div class="table-responsive">
<table class="table table-bordered table-striped">
  <thead class="bg-primary stoic-color">
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Entity Type</th>
      <th scope="col">Entity ID</th>
      <th scope="col">Device Type</th>
      <th scope="col">Device ID</th>
      <th scope="col">Mapping</th>
      <th scope="col">Broker</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody id="devices-table">
    {% for association in associations %}
    <tr>
      <th  class="align-middle" scope="row">{{ forloop.counter0 }}</th>
      <td class="align-middle">{{ association.id }}</td>
      <td class="align-middle">{{ association.entity_type }}</td>
      <td class="align-middle">{{ association.entity_id }}</td>
      <td class="align-middle">{{ association.device_type }}</td>
      <td class="align-middle">{{ association.device_id }}</td>
      {% if not association.mapping %}
      <td class="align-middle"><span class="badge badge-pill badge-primary">{{ "generic" }}</div></td>
      {% else %}
      <td class="align-middle">
      {% for attr, map in association.mapping.items %}
      {% comment %} [{{ attr }}] => ({{ map.name }},{{ map.type }})<br/> {% endcomment %}
      <span class="badge badge-pill badge-success">{{ attr }}</span> <i class="fas fa-long-arrow-alt-right"></i> <span class="badge badge-pill badge-warning">{{ map.name }}</span> <span class="badge badge-pill badge-info">{{ map.type }}</span><br/>
      {% endfor %}
      </td>
      {% endif %}
      <td class="align-middle">{{ association.broker }}</td>
      <td class="align-middle">
            <!-- <button onclick="location.href='{=% url 'manager:index' %}';" type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button> -->
          <button onclick="location.href='{% url 'manager:associations_delete' %}?broker={{ association.broker }}&id={{ association.id }}';" type="button" class="btn btn-danger btn-sm"><i class="fas fa-trash" aria-hidden="true"></i></button>
      </td>
    </tr>
    {% endfor %}
  <tfoot class="bg-primary stoic-color">
    <tr>
      <td scope="col">#</td>
      <td scope="col">ID</td>
      <td scope="col">Entity Type</td>
      <td scope="col">Entity ID</td>
      <td scope="col">Device Type</td>
      <td scope="col">Device ID</td>
      <td scope="col">Mapping</td>
      <td scope="col">Broker</td>
      <td scope="col">Action</td>
    </tr>
  </tfoot>
  </tbody>
</table>
</div>
<!-- <button type="button" class="btn btn-primary" onclick="location.href='{=% url 'manager:new' %}';">New devices</button> -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_association">New link</button>

<div class="modal fade" id="new_association" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">New link</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="new_association_form" method="post" action="{% url 'manager:associations_new' %}">
          {% csrf_token %}
          {{ form.errors }}
          {{ form|bootstrap }}
          <label class="control-label">Attributes</label>
          <table class="table table-bordered">
            <thead class="bg-primary stoic-color">
              <tr>
                <th scope="col">Device attribute</th>
                <th scope="col">Entity attribute</th>
                <th scope="col">Entity attribute type</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody id="attrs_forms">
            </tbody>
          </table>
          <div class="form-group">
            <button id="add_attr_form" type="button" class="btn btn-primary">Add map</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button id="new_association_submit" type="button" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
<script>
    $(() => {
      $("#devices-filter").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#devices-table tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });

      let _devices = {}
      let _entities = {}
      let broker_id = null

      $("#broker_id").on('change', (event)=>{
        //event.stopPropagation()
        $("#new_association_submit").prop( "disabled", true )
        $("#device_type").prop( "disabled", true );
        $("#device_id").prop( "disabled", true );
        $("#entity_type").prop( "disabled", true );
        $("#entity_id").prop( "disabled", true );
        $("#add_attr_form").prop( "disabled", true )
        $("#attrs_forms").find("input").prop( "disabled", true )

        broker_id = $("#broker_id").val()
        $.ajax({
            method: "GET",
            url: "{% url 'manager:entities_index' %}",
            headers: {
              'Accept': 'application/json'
            }
          }).done(entities => {
            $("#entity_type").empty()
            _entities = entities
            let types = entities.filter(dev => {
              return dev.broker == broker_id
            })
            .map(dev => {
              return dev.type
            })
            types = new Set(types)
            types.forEach((type)=>{
              $("#entity_type").append(new Option(type, type))
            })
            $("#entity_type").prop("disabled", false)
            $("#entity_type").trigger('change')
          })

        $.ajax({
            method: "GET",
            url: "{% url 'manager:devices_index' %}",
            headers: {
              'Accept': 'application/json'
            }
          }).done(devices => {
            $("#device_type").empty()
            _devices = devices
            let types = devices.filter(dev => {
              return dev.broker == broker_id
            })
            .map(dev => {
              return dev.type
            })
            types = new Set(types)
            types.forEach((type)=>{
              $("#device_type").append(new Option(type, type))
            })
            $("#device_type").prop("disabled", false)
            $("#device_type").trigger('change')
          })
      }).trigger('change')

      $("#device_type").on('change',()=>{
        $("#device_id").empty()
        _devices.forEach((device)=>{
          if (device.type == $("#device_type").val() && device.broker == broker_id)
            $("#device_id").append(new Option(device.id, device.id))
        })
        $("#device_id").prop("disabled", false)
        $("#add_attr_form").prop( "disabled", false )
        $("#attrs_forms").find("input").prop( "disabled", false )
        $("#new_association_submit").prop( "disabled", false )
      })

      $("#entity_type").on('change',()=>{
        $("#entity_id").empty()
        _entities.forEach((entity)=>{
          if (entity.type == $("#entity_type").val() && entity.broker == broker_id)
            $("#entity_id").append(new Option(entity.id, entity.id))
        })
        $("#entity_id").prop("disabled", false)
      })

      $('#new_association').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var recipient = button.data('project') // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        if (recipient != undefined) {
          modal.find('.modal-title').text('New message to ' + recipient)
          modal.find('.modal-body input').val(recipient)
        }
        modal.find('#new_association_submit').click(function() {
          if (modal.find("#new_association_form")[0].reportValidity())
            modal.find("#new_association_form").trigger('submit')
        })
        console.log(modal.find('#new_association_submit'))
      })

      $('#add_attr_form').on('click', function(event) {
        var time = $('#attrs_forms')[0].childElementCount
        var tag = `
              <tr>
                <td  class="align-middle" scope="row"><input type="text" name="attrs[${time}][device_attr]" maxlength="30" class=" form-control" required></td>
                <td class="align-middle"><input type="text" name="attrs[${time}][entity_attr]" maxlength="30" class=" form-control" required></td>
                <td class="align-middle"><input type="text" name="attrs[${time}][entity_attr_type]" maxlength="30" class=" form-control" required></td>
                <td class="align-middle">
                  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                    <div class="btn-group mr-2" role="group" aria-label="First group">
                      <button onclick="$(this).closest('tr').remove()" type="button" class="btn btn-danger"><i class="fas fa-trash" aria-hidden="true"></i></button>
                    </div>
                  </div>
                </td>
              </tr>`
        $('#attrs_forms').append(tag)
      })
    });
</script>
{% endblock %}

stoic-front/manager/templates/associations/new.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block content %}
<h1>Devices</h1>
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    {% if action == 'new' %}
        <input type="submit" role="button" class="btn btn-primary" value="Create">
    {% else %}
        <input type="submit" role="button" class="btn btn-primary" value="Update">
    {% endif %}
</form>
{% endblock %}