stoic-front/brokers/urls.py
from django.urls import path
from . import views

app_name = 'brokers'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('schema/<broker_type>', views.schema, name='schema')
]

stoic-front/manager/urls.py
from django.urls import path, re_path
from . import views

app_name = 'manager'

urlpatterns = [
    # -- BROKERS --
    #path('brokers', views.brokers_index, name='brokers_index'),
    #path('brokers/new', views.brokers_new, name='brokers_new'),
    #path('brokers/delete', views.brokers_delete, name='brokers_delete'),
    # -- DEVICES --
    path('devices', views.devices_index, name='devices_index'),
    path('devices/new', views.devices_new, name='devices_new'),
    path('devices/delete', views.devices_delete, name='devices_delete'),
    # -- ENTIDADES --
    path('entities', views.entities_index, name='entities_index'),
    path('entities/new', views.entities_new, name='entities_new'),
    path('entities/edit', views.entities_edit, name='entities_edit'),
    path('entities/delete', views.entities_delete, name='entities_delete'),
    # -- ASSOCIATIONS --
    path('associations', views.associations_index, name='associations_index'),
    path('associations/new', views.associations_new, name='associations_new'),
    path('associations/delete', views.associations_delete, name='associations_delete'),
    # -- TASKS --
    path('tasks', views.tasks_index, name='tasks_index'),
    path('tasks/new', views.tasks_new, name='tasks_new'),
    path('tasks/edit', views.tasks_edit, name='tasks_edit'),
    path('tasks/delete', views.tasks_delete, name='tasks_delete'),
    # -- DASHBOARD --
    path('dashboard', views.dashboard_index, name='dashboard_index'),
    path('dashboard/update', views.dashboard_update)
]
'''
Autorização para utilizar a reserva do auxilio a pesquisa
Encaminhar a solicitação pelo sistema Agilis fapesp.br/rt 21 de dezembro
'''

stoic-front/myfront/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Stoic Front API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="Unlicensed"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('brokers/', include('brokers.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

stoic-front/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('edit', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('activate', views.activate, name='activate')
]

stoic-front/theme/models.py
from django.db import models

# Create your models here.

stoic-front/theme/views.py
from django.shortcuts import render

# Create your views here.

stoic-front/theme/templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap %}
{% block content %}
<div class="row">
    <div class="col-6 stoic-text-index">
        <h1>Welcome to STOIC</h1>
        <p>Log in and start creating new multiplatform IoT applications right now!</p>
        <div class="stoic-img-container">
        <img class="stoic-img" src="{% static 'img/greek-column-black.svg' %}">
        </div>
    </div>
    {% if not user.is_authenticated %}
    <div class="col-6">
        {% csrf_token %}
        {{ form|bootstrap }}
    </div>
    {% endif %}
</div>
{% endblock %}

stoic-front/theme/templates/layout-bkp.html
{% load static %}
{% load bootstrap %}
<html>

<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><img class="stoic-icon" src="{% static 'img/greek-column.svg' %}"> STOIC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item active">
                    <a class="nav-link" href="http://google.com">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="/accounts/logout">Logout</a>
                    </div>
                  </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> Login
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <form class="px-4 py-3" method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {{ form.username|bootstrap }}
                            {{ form.password|bootstrap }}
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot password?</a>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            {% if user.is_authenticated %}
            <div id="sidebar" class="col-2">
                <nav class="navbar navbar-inverse bg-light flex-column">
                    <!-- Links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <!-- <a class="nav-link" href="{% url 'projects:index' %}"><i class="fa fa-file-code-o" aria-hidden="true"></i> Projects</a> -->
                            <a class="nav-link" href="{% url 'brokers:index' %}"><i class="fa fa-file-code-o" aria-hidden="true"></i> Platforms</a>
                        </li>
                        {#% if active %#}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'manager:devices_index' %}"><i class="fa fa-cogs" aria-hidden="true"></i> Devices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'manager:entities_index' %}"><i class="fa fa-object-group" aria-hidden="true"></i> Entities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'manager:associations_index' %}"><i class="fa fa-link" aria-hidden="true"></i> Associations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'manager:tasks_index' %}"><i class="fa fa-tasks" aria-hidden="true"></i> Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'manager:dashboard_index' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i> Dashboard</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link " href="#">Link 3</a>
                        </li> -->
                        {#% endif %#}
                    </ul>
                </nav>
            </div>
            {% endif %}
            <div class="col-10">
                <div id="header">
                    <!-- <h1><a href="/">Django CRUD Example</a></h1> -->
                </div><!-- header -->
                <br/>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

stoic-front/theme/templates/layout.html
{% load static %}
{% load bootstrap %}
<!doctype html>
<html lang="en">
  <head>
    <title>STOIC</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} <script src="{% static 'js/jquery.min.js' %}"></script> {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body>

		<div class="wrapper d-flex align-items-stretch">
            {% if user.is_authenticated %}
			<nav id="sidebar" class="active">
				<h1><a href="/" class="logo">S.</a></h1>
                <ul class="list-unstyled components mb-5">
                    <li class="active">
                        <a href="{% url 'brokers:index' %}"><span class="fas fa-server"></span> Platforms</a>
                    </li>
                    <li>
                        <a href="{% url 'manager:devices_index' %}"><span class="fa fa-cogs"></span> Devices</a>
                    </li>
                    <li>
                        <a href="{% url 'manager:entities_index' %}"><span class="fa fa-object-group"></span> Entities</a>
                    </li>
                    <li>
                        <a href="{% url 'manager:associations_index' %}"><span class="fa fa-link"></span> Links</a>
                    </li>
                    <li>
                        <a href="{% url 'manager:tasks_index' %}"><span class="fa fa-tasks"></span> Tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'manager:dashboard_index' %}"><span class="fas fa-chart-line"></span> Charts</a>
                    </li>
                </ul>

        <div class="footer">
        	<p>
					  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					</p>
        </div>
    	</nav>
        {% endif %}
        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            {% if user.is_authenticated %}
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
            {% endif %}
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="/accounts/logout">Logout</a>
                    </div>
                  </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> Login
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <form class="px-4 py-3" method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {{ form.username|bootstrap }}
                            {{ form.password|bootstrap }}
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot password?</a>
                    </div>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        {% block content %}
        {% endblock %}
      </div>
		</div>

    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>